apiVersion: v1
kind: Service
metadata:
  name: catalog-service-spring
  namespace: novamart
  labels:
    app: catalog-service-spring
spec:
  type: ClusterIP
  selector:
    app: catalog-service-spring
  ports:
    - name: http
      port: 80
      targetPort: 8080

