novamart:
  security:
    cognito:
      issuer: "https://cognito-idp.us-east-2.amazonaws.com/us-east-2_o1EqblrWu"
      audience: "2pos9ql83uc73oejcirvrb6d1g"

spring:
  datasource:
    # Use environment variables when running in Docker/EKS; fall back to local defaults.
    url: ${DB_URL:jdbc:postgresql://catalog-postgres:5432/novamart_catalog}
    username: ${DB_USERNAME:novamart}
    password: ${DB_PASSWORD:dev-password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${novamart.security.cognito.issuer}
