version: "3.8"

services:
  dynamodb:
    image: amazon/dynamodb-local
    container_name: novamart-inventory-dynamodb
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-inMemory"]
    ports:
      - "8000:8000"

  localstack:
    image: localstack/localstack:3.0
    container_name: novamart-inventory-localstack
    environment:
      SERVICES: events
      AWS_DEFAULT_REGION: us-east-2
    ports:
      - "4566:4566"
    volumes:
      - inventory_localstack_data:/var/lib/localstack

volumes:
  inventory_localstack_data:
