version = 0.1

[default.deploy.parameters]
stack_name = "novamart-shipping-service"
resolve_s3 = true
s3_prefix = "novamart-shipping-service"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.global.parameters]
region = "us-east-2"
