spring:
  application:
    name: order-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/novamart_orders}
    username: ${DB_USERNAME:novamart}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8081

novamart:
  events:
    # Name of the EventBridge event bus for NovaMart (adjust for your account).
    bus-name: ${NOVAMART_EVENT_BUS:default}
    source: "novamart.order-service"

aws:
  region: ${AWS_REGION:us-east-1}

